# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20171223_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='name',
            field=models.CharField(default='Burger King', max_length=120),
            preserve_default=False,
        ),
    ]
