# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
